### ISSUE TITLE
Interface Design - UI/UX

### ISSUE THREAD

**Issue by tolstenko** [InfiniBrains/MedicalImageViewer#1]
Design how the interface will look like. Here go some references:
- Radiant viewer - smallest viewer, and still robust
- OHIF - https://github.com/OHIF/Viewers
- Osirix - more robust
- 3d slicer https://www.slicer.org is the more reliable in terms of extending via python, editing tool and manipulating medical images
- mango https://mangoviewer.com/mango.html is the most straight to the point viewer
- POSTDICOM
- Horos

Read more here. https://www.postdicom.com/en/blog/top-25-free-dicom-viewers

**Comment by sudo-kunal** [comment]
Hello there,

I'm willing to contribute in designing the viewer interface. Please help me understand the elements to showcase on the interface. 

Thanks and Regards,
Kunaaal.
